export const HQ_PAGES = {
  AUTH: '/',
  DASHBOARD: '/dashboard',
  ME: '/me',
  REGIONS: '/regions',
  AD_SETTING: '/ad-setting',
  AD_LOCATIONS: '/ad-locations',
  AD_BOARDS: '/ad-boards',
  AD_REQUESTS: '/ad-requests',
  AD_LOCATION_MODIFICATION_REQUESTS: '/ad-requests/modification/location',
  AD_BOARD_MODIFICATION_REQUESTS: '/ad-requests/modification/board',
  AD_APPROVE_REQUESTS: '/ad-requests/approve',
  REPORTS: '/reports',
  ACCOUNT_MANAGEMENT: '/account-management',
};
