export const OFFICER_PAGES = {
  AUTH: '/',
  SOCIAL_AUTH: '/social-auth',
  DASHBOARD: '/dashboard',
  ADS_BOARD: '/ad-boards',
  ADS_BOARD_EDIT: '/ad-boards/edit',
  ADS_LOCATION: '/ad-locations',
  REPORT: '/reports',
  APPROVE_LIST: '/approves',
  APPROVE_DETAIL: '/approves/detail',
  NEW_APPROVE: '/approves/new',
  ME: '/me',
  PERSONAL_INFORMATION: '/me/personal-information',
  CHANGE_PASSWORD: '/me/change-password',
};
