import './global.css';
import AccessPageTemplate from '@presentational/templates/AccessPageTemplate';

export const metadata = {
  title: 'Welcome to auth-ua',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AccessPageTemplate>{children}</AccessPageTemplate>
      </body>
    </html>
  );
}
